baseURL = 'https://wreckd.runs.nz/'
languageCode = 'en-nz'
title = "WREC'kd"
theme = 'ananke'

[params]
  description = "Wellington running club"
  background_color_class = "bg-white"
  body_classes = "bg-white"
  featured_image = ""
  show_reading_time = false
  custom_css = ["custom.css"]

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Fixtures"
    url = "/fixtures/"
    weight = 20
  [[menu.main]]
    name = "Faq"
    url = "/faq/"
    weight = 20
  [[menu.main]]
    name = "Join"
    url = "/join/"
    weight = 30
